export enum UserActiveType {
  ACTIVE = "ACTIVE",
  IN_MODERATION = "IN_MODERATION",
  BANNED = "BANNED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  FILLS_OUT_THE_APPLICATION = "FILLS_OUT_THE_APPLICATION",
}

export enum UserActiveTypeIDs {
  ACTIVE = 1,
  IN_MODERATION = 2,
  BANNED = 3,
  EMAIL_NOT_VERIFIED = 4,
  FILLS_OUT_THE_APPLICATION = 5,
}
