import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { dir } from "i18next";

import Header from "@/src/widgets/Header";
import ReduxProvider from "@/src/app";
import RefreshSessionProvider from "@/src/app/providers/RefreshSessionProvider";
import Footer from "@/src/widgets/Footer";
import { languages } from "../i18n/settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TutorApp",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map(lng => ({ lng }));
}

export default async function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  params: { lng: string };
  children: React.ReactNode;
}>) {
  // const { t } = await useTranslation(lng, "header");
  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <RefreshSessionProvider>
            <div className="wrapper">
              <Header lng={lng} />
              <main>{children}</main>
              <Footer lng={lng} />
            </div>
          </RefreshSessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
